apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: default
data:
  default.conf: | # 이하 nginx의 설정
    server {
        listen 80;
        server_name _;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        # -----------------------------
        # Python backend proxy
        # -----------------------------
        location /run/python/ {
            # [핵심 1] k8s의 기본 내부 DNS 서버 주소 명시 (나의 환경: 10.96.0.10)
           # resolver 10.96.0.10 valid=5s;
            # k3s의 기본DNS 주소
             resolver 10.43.0.10 valid=5s;

            # [핵심 2] 주소를 변수로 선언 (이렇게 하면 Nginx가 시작할 때 에러표시 안함)
            set $backend_url http://py-code-run.default.svc.cluster.local:8080/run;

            # 변수를 사용해서 호출 (Lazy Resolve)
            proxy_pass $backend_url;
            
            proxy_http_version 1.1;
            # Host 헤더는 필수!
            proxy_set_header Host py-code-run.default.svc.cluster.local;
            
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_connect_timeout 10s;
            proxy_read_timeout 120s;
        }
    }
